Skipping source - missing url or followers: 1
Skipping source - missing url or followers: 2
Error validating source: TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at <anonymous> (/home/runner/workspace/server/routes.ts:423:33)
    at Array.filter (<anonymous>)
    at <anonymous> (/home/runner/workspace/server/routes.ts:416:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async <anonymous> (/home/runner/workspace/server/routes.ts:482:23) {
  code: 'ERR_INVALID_URL',
  input: 'vk.com/grindin'
}
Error validating source: TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at <anonymous> (/home/runner/workspace/server/routes.ts:423:33)
    at Array.filter (<anonymous>)
    at <anonymous> (/home/runner/workspace/server/routes.ts:416:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async <anonymous> (/home/runner/workspace/server/routes.ts:482:23) {
  code: 'ERR_INVALID_URL',
  input: 't.me/s/livedune'
}
Error validating source: TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at <anonymous> (/home/runner/workspace/server/routes.ts:423:33)
    at Array.filter (<anonymous>)
    at <anonymous> (/home/runner/workspace/server/routes.ts:416:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async <anonymous> (/home/runner/workspace/server/routes.ts:482:23) {
  code: 'ERR_INVALID_URL',
  input: 'levelkitchen.com'
}
Error validating source: TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at <anonymous> (/home/runner/workspace/server/routes.ts:423:33)
    at Array.filter (<anonymous>)
    at <anonymous> (/home/runner/workspace/server/routes.ts:416:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async <anonymous> (/home/runner/workspace/server/routes.ts:482:23) {
  code: 'ERR_INVALID_URL',
  input: 'r/PersonalizedDiet'
}
Error validating source: TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at <anonymous> (/home/runner/workspace/server/routes.ts:423:33)
    at Array.filter (<anonymous>)
    at <anonymous> (/home/runner/workspace/server/routes.ts:416:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async <anonymous> (/home/runner/workspace/server/routes.ts:482:23) {
  code: 'ERR_INVALID_URL',
  input: 'x.com/PersonalHealth'
}
No valid sources found in response for персонализированный рацион